services:
  db:
    image: postgres:16
    container_name: embspg
    environment:
      POSTGRES_USER: embs
      POSTGRES_PASSWORD: embs
      POSTGRES_DB: embs
    ports:
      - "5433:5432"
    volumes:
      - embs_pgdata:/var/lib/postgresql/data

volumes:
  embs_pgdata: